server:
  backend: local

prometheus:
  enable: true
  min_version: 2.30.0
  install_version: 2.54.1
  prometheus_port: 9090
  retention_time: 30d
  config_file: ${service_root}/services/prometheus/prometheus.yml

otel:
  otel_port: 4318

tempo:
  enable: true
  min_version: 2.0.0
  install_version: 2.6.1
  query_port: 3200
  retention_time: 30d
  config_file: ${service_root}/services/tempo/tempo.yaml

grafana:
  enable: true
  min_version: 13.0.0
  install_version: 13.0.0
  port: 3000
  config_file: ${service_root}/services/grafana/grafana.ini
  provisioning_dir: ${service_root}/services/grafana/provisioning
  dashboards_dir: ${service_root}/services/grafana/dashboards

