apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://host.docker.internal:${RLINSIGHT_PROMETHEUS_PORT}
    editable: true
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    isDefault: false
    url: http://host.docker.internal:${RLINSIGHT_TEMPO_QUERY_PORT}
    editable: true
